version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - aws --version
      - docker --version

  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 828862865552.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app:latest 828862865552.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:latest

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push 828862865552.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:latest
      - echo Build completed successfully

artifacts:
  base-directory: .
  files:
    - '**/*'
