version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.1/2023-04-19/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - echo Installing AWS CLI...
      - apt-get update && apt-get install -y awscli

  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 828862865552.dkr.ecr.ap-south-1.amazonaws.com
      - echo Updating kubeconfig for EKS...
      - aws eks update-kubeconfig --region ap-south-1 --name brain-tasks-cluster
      - echo Checking kubectl connection...
      - kubectl get nodes

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app:latest 828862865552.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push 828862865552.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:latest
      - echo Deploying to Kubernetes cluster...
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
      - echo Deployment successful!
